# Generated by Django 5.1.3 on 2024-11-23 11:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankWallet',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('balance', models.FloatField(default=uuid.uuid4, verbose_name='Текущий баланс')),
            ],
        ),
    ]
