services:
  app:
    build: .
    command: gunicorn BankApp_test.wsgi:application --bind 0.0.0.0:8000
    container_name: bank_app
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
    ports:
      - 127.0.0.1:8000:8000

  db:
    image: postgres
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    restart: always
    env_file:
      - .env
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: