# Generated by Django 5.1.3 on 2024-11-23 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущий баланс'),
        ),
        migrations.AlterField(
            model_name='bankwallet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
